#!/bin/bash

export RTE_TARGET=i686-default-linuxapp-gcc
export RTE_SDK=/home/rajnesh/Desktop/dpdk-1.6.0r2

umount /mnt/huge
rm -rf /mnt/huge

mkdir -p /mnt/huge
mount -t hugetlbfs nodev /mnt/huge
echo 64 > /sys/kernel/mm/hugepages/hugepages-4096kB/nr_hugepages

# without huge page l2fwd will not work.

./build/tcp_stack -c 0xf -n 4 -- -p 0x3
